"""empty message

Revision ID: 0e51c1f9a3a9
Revises: 6f52d11e0b6d
Create Date: 2023-11-21 16:36:08.295572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e51c1f9a3a9'
down_revision = '6f52d11e0b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_first_name_key', type_='unique')
        batch_op.drop_constraint('user_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('user_first_name_key', ['first_name'])

    # ### end Alembic commands ###
