"""empty message

Revision ID: 423d926c2a29
Revises: be2e8d489eef
Create Date: 2023-11-18 01:29:28.867089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423d926c2a29'
down_revision = 'be2e8d489eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'friend', ['friend_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('friend_id')

    # ### end Alembic commands ###
