"""empty message

Revision ID: 6f52d11e0b6d
Revises: 656ac6c7e402
Create Date: 2023-11-21 16:34:06.382023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f52d11e0b6d'
down_revision = '656ac6c7e402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_member',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_friend',
    sa.Column('user_1', sa.Integer(), nullable=True),
    sa.Column('user_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], )
    )
    op.drop_table('friend')
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='members_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='members_pkey')
    )
    op.create_table('friend',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_a', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_a'], ['user.id'], name='friend_user_a_fkey'),
    sa.PrimaryKeyConstraint('id', name='friend_pkey')
    )
    op.drop_table('user_friend')
    op.drop_table('group_member')
    # ### end Alembic commands ###
